// <auto-generated />
using System;
using FileService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Migrations
{
    [DbContext(typeof(FileDbContext))]
    partial class FileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.Entities.FileItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackupUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileSHA256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("RemoteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("FileSHA256Hash", "FileSizeInBytes");

                    b.ToTable("FileItems");
                });

            modelBuilder.Entity("FileService.Domain.Entities.FileItem", b =>
                {
                    b.OwnsOne("FileService.Domain.FileIdentifier", "FileIdentifier", b1 =>
                        {
                            b1.Property<Guid>("FileItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(true)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("FileName");

                            b1.Property<string>("FileType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .IsUnicode(false)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("FileType");

                            b1.Property<string>("ProjectName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(false)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("ProjectName");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasMaxLength(32)
                                .IsUnicode(false)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("UserName");

                            b1.Property<string>("VersionName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .IsUnicode(false)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("VersionName");

                            b1.HasKey("FileItemId");

                            b1.ToTable("FileItems");

                            b1.WithOwner()
                                .HasForeignKey("FileItemId");
                        });

                    b.Navigation("FileIdentifier")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
